---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      northbay-nginx=northbayacr.azurecr.io/northbay-nginx
    argocd-image-updater.argoproj.io/northbay-nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/northbay-nginx.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/rizwan2017/northbay-helm.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://northbay-aks-dns-x19y8y76.hcp.eastus.azmk8s.io:443
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
